### ISSUE TITLE
Unable to clear "connected to 1 server" notification

### ISSUE THREAD

**Issue by chreekat** [tilal6991/HoloIRC#121]
Please use notifications for alerting events, not for showing statuses.

**Comment by tilal6991** [comment]
To keep the app running as a background service Android requires a notification to be displayed - there's no way around it.

**Comment by chreekat** [comment]
Thanks for the info. How do apps like Twitter and hangouts run in the background? I apologize, I am unfamiliar with android development.

**Comment by tilal6991** [comment]
Twitter and Hangouts use push notifications. They are not actually running in the background - they simply register with the system to push a notification when one arrives. However, IRC requires a persistent TCP connection which requires the use of a service to prevent the system from killing the app and closing the connection.

**Comment by chreekat** [comment]
Dear Android,

:|

Sincerely,
- Bryan
