### ISSUE TITLE
After the update, I cannot connect to ZNC servers.

### ISSUE THREAD

**Issue by ElpoRia** [tilal6991/HoloIRC#136]
http://puu.sh/nKNWo/787519a4be.png

When I needs to login the server, message field disabled so I cannot type passwords.

**Comment by maniac103** [comment]
Interesting. You should be able to put your password in settings anyway, but what shouldn't happen here is that the server still is in 'connecting' state. It should be 'connected'.

**Comment by ElpoRia** [comment]
http://puu.sh/nKOIH/a3c4e5534e.png
Hmm, it showed disconnected state before the authentification on the previous version too.

Then, where can i add my passwords to login?
adding "/quote PASS user:password" at settings -password doesn't seems work.

**Comment by maniac103** [comment]
ZNC's password format usually is 'user/network:password'. See here: http://wiki.znc.in/FAQ#Why_do_I_get_an_.22Incorrect_Password.22_every_time_I_connect_even_though_my_pass_is_correct.3F

**Comment by ElpoRia** [comment]
nono that's not a problem.

Try it yourself 
Server addr : 148.163.102.23
Port : 44312  (no ssl)

**Comment by tilal6991** [comment]
Yeah the status system is a bit messed up. I don't know why your password is not going through. I also use a znc and passwords work fine for me. We might reenable the box as soon as the socket connection is established.

**Comment by ElpoRia** [comment]
Thank you.. 
I gonna use previous version until the problem is resolved.

**Comment by maniac103** [comment]
@ElpoRia Can you please leave the server accessible like that? I can repro the issue with your server and want to debug this.

**Comment by ElpoRia** [comment]
@maniac103 Use this, I've created testuser with rizon irc server.

148.163.102.23 , 44312 port
username : testuser1
pw : password123

You can connect like this.
/quote PASS testuser1/rizon:password123

**Comment by maniac103** [comment]
See the above mentioned pull request. With that, you still need to enter your ZNC password in HoloIRC's settings, but at least the server doesn't get stuck in that weird 'connecting' state.

**Comment by tilal6991** [comment]
https://github.com/tilal6991/HoloIRC/commit/dbf41b9345b2a2b3fd356d2525cc36d5bdfcf7b5 should fix this issue hopefully. It's slightly more scalable than the PR above.

**Comment by ElpoRia** [comment]
Now, i can connect to the server.
It was because of my little mistake, sorry.
