### ISSUE TITLE
Nonstandard CTCP VERSION response

### ISSUE THREAD

**Issue by mappu** [tilal6991/HoloIRC#140]
Hi,

In response to `CTCP VERSION` requests, HoloIRC sends

`NOTICE ctcpSender \x01VERSION :Relay:1.0:Android\x01`

But shouldn't the colon be before the CTCP header?

For comparison, HexChat sends the following

`NOTICE ctcpSender :\x01VERSION HexChat 2.12.1 [x64] / Microsoft Windows 10 Pro (x64) [Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz (3.60GHz)]\x01`

**Comment by mappu** [comment]
Tested with 4.1.0 from Play store (`com.fusionx.lightirc`)

**Comment by Techman** [comment]
Yes, the colon is in the wrong spot. CC: @tilal6991

**Comment by LalitMaganti** [comment]
Correct. Please feel free to send a PR in Relay to fix. Should be a 1 line change.
