### ISSUE TITLE
Build Issue: Could not create plugin of type 'AppPlugin'

### ISSUE THREAD

**Issue by tuennes** [tilal6991/HoloIRC#149]
Whole error message:

Plugin is too old, please update to a more recent version, or set ANDROID_DAILY_OVERRIDE environment variable to "78da0c009faeffd92367514bbd60a9f39c3dcd64"

FAILURE: Build failed with an exception.

* Where:
Build file '/home/xxx/holoirc/android/build.gradle' line: 17

* What went wrong:
A problem occurred evaluating project ':android'.
> Failed to apply plugin [id 'com.android.application']
   > Could not create plugin of type 'AppPlugin'.

I changed due to newer version already:
classpath 'com.android.tools.build:gradle:2.3.0-alpha1'

(current build system is to find here: http://tools.android.com/tech-docs/new-build-system)

Thanks for help!!

**Comment by dgw** [comment]
I'm afraid help is unlikely. @tilal6991 has stated in other threads that this app is no longer being developed. It's meant to be replaced by [tilal6991/channels](https://github.com/tilal6991/channels), but little forward progress has been made in the last year.

**Comment by tuennes** [comment]
Thanks dgw!
